c_stdlib_version:  # [win]
  - 2022.12        # [win]

c_compiler:    # [win]
  - vs2022     # [win]
cxx_compiler:  # [win]
  - vs2022     # [win]

# Need at least libgrpc 1.72.0 to build bazel 8+
libgrpc:
  - 1.74.1
# Need at least abseil 20250127.1 to build bazel 8+
libabseil:
  - 20250814.1
libprotobuf:
  - 6.33.0